rootProject.name = "easy-spring-auth"
includeBuild("lab-1")
includeBuild("lab-2")
includeBuild("lab-3")
includeBuild("lab-4")
includeBuild("lab-5")
includeBuild("lab-6")
includeBuild("lab-7")
includeBuild("lab-8")
includeBuild("lab-9")
includeBuild("lab-completed")